services:
  - type: web
    name: edutena-sms
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: edutena-db
          property: connectionString

databases:
  - name: edutena-db
    region: oregon